# Useful Links
Extract images http://theautomatic.net/2019/10/14/how-to-read-word-documents-with-python/

Step 1: Need to read through all a href links, and download the documents<br>
Step 2: Read the documents from the folders and extract text

# 1. Working with Documents

In [1]:
import numpy as np
import pandas as pd

from docx2python import docx2python

In [2]:
# extract docx content
doc_result = docx2python('zen_of_python.docx', extract_image=False)

In [3]:
# get separate components of the document
doc_result_body = doc_result.body
print(f"This is the Body:\n{doc_result_body}\n")

# get the table text
print(f"This is the First Element:\n{doc_result_body[0]}]\n")
 
# get the text from Zen of Python
print(f"This is the Second Element:\n{doc_result_body[1]}\n")

This is the Body:
[[[['Field1'], ['Field2']], [['Info1'], ['Info2']], [['Info3'], ['Info4']]], [[['Header Title', '', 'Paragraph written over here.', '--\tList 1', '--\tList 2', '', 'Sub Heading', '1)\tPoint One', '2)\tPoint Two', '3)\tPoint Three']]]]

This is the First Element:
[[['Field1'], ['Field2']], [['Info1'], ['Info2']], [['Info3'], ['Info4']]]]

This is the Second Element:
[[['Header Title', '', 'Paragraph written over here.', '--\tList 1', '--\tList 2', '', 'Sub Heading', '1)\tPoint One', '2)\tPoint Two', '3)\tPoint Three']]]

In [4]:
# convert this result into a tabular format using pandas
df = pd.DataFrame(doc_result_body[0][1:])

df

         0        1
0  [Info1]  [Info2]
1  [Info3]  [Info4]

In [5]:
# applymap method to apply the lambda function below to every cell in the data frame. This function gets the individual value within the list in each cell and removes all instances of “\t”.
df = df.applymap(lambda val: val[0].strip("\t"))

df

       0      1
0  Info1  Info2
1  Info3  Info4

In [6]:
# change the column headers to what we see in the Word file
df.columns = [val[0].strip("\t") for val in doc_result.body[0][0]]

df

  Field1 Field2
0  Info1  Info2
1  Info3  Info4

In [7]:
# get all text in a single string
doc_result.text

'Field1\n\nField2\n\nInfo1\n\nInfo2\n\nInfo3\n\nInfo4\n\nHeader Title\n\n\n\nParagraph written over here.\n\n--\tList 1\n\n--\tList 2\n\n\n\nSub Heading\n\n1)\tPoint One\n\n2)\tPoint Two\n\n3)\tPoint Three'

In [8]:
# get metadata about the file using the properties attribute
doc_result.properties

{'title': None,
 'subject': None,
 'creator': 'Andy Ang',
 'keywords': None,
 'description': None,
 'lastModifiedBy': 'Andy Ang',
 'revision': '7',
 'created': '2020-09-14T02:36:00Z',
 'modified': '2020-09-14T03:02:00Z'}

In [9]:
# get the headers
doc_result.header
 
# get the footers
doc_result.footer

# get foot notes
doc_result.footnotes

[]

In [10]:
# get html, does not currently support table-related tags
doc_html_result = docx2python('zen_of_python.docx', html = True)

doc_html_result.body

[[[['Field1'], ['Field2']], [['Info1'], ['Info2']], [['Info3'], ['Info4']]],
 [[['Header Title',
    '',
    'Paragraph written over here.',
    '--\tList 1',
    '--\tList 2',
    '',
    'Sub Heading',
    '1)\tPoint One',
    '2)\tPoint Two',
    '3)\tPoint Three']]]]

# 2. Working with PDF

In [11]:
import PyPDF2

f = open('US_Declaration.pdf','rb')
pdf_reader = PyPDF2.PdfFileReader(f)

pdf_reader.numPages

page_one = pdf_reader.getPage(0)

page_one_text = page_one.extractText()

print(page_one_text)

f.close()

Declaration of IndependenceIN CONGRESS, July 4, 1776. The unanimous Declaration of the thirteen united States of America, When in the Course of human events, it becomes necessary for one people to dissolve the
political bands which have connected them with another, and to assume among the powers of the
earth, the separate and equal station to which the Laws of Nature and of Nature's God entitle

them, a decent respect to the opinions of mankind requires that they should declare the causes

which impel them to the separation.
We hold these truths to be self-evident, that all men are created equal, that they are endowed by

their Creator with certain unalienable Rights, that among these are Life, Liberty and the pursuit
of Happiness.ŠThat to secure these rights, Governments are instituted among Men, deriving

their just powers from the consent of the governed,ŠThat whenever any Form of Government
becomes destructive of these ends, it is the Right of the People to alter or to abolish it, and to
institute new Government, laying its foundation on such principles and organizing its powers in
such form, as to them shall seem most likely to effect their Safety and Happiness. Prudence,

indeed, will dictate that Governments long established should not be changed for light and
transient causes; and accordingly all experience hath shewn, that mankind are more disposed to
suffer, while evils are sufferable, than to right themselves by abolishing the forms to which they

are accustomed. But when a long train of abuses and usurpations, pursuing invariably the same
Object evinces a design to reduce them under absolute Despotism, it is their right, it is their duty,
to throw off such Government, and to provide new Guards for their future security.ŠSuch has
been the patient sufferance of these Colonies; and such is now the necessity which constrains

them to alter their former Systems of Government. The history of the present King of Great

Britain is a history of repeated injuries and usurpations, all having in direct object the
establishment of an absolute Tyranny over these States. To prove this, let Facts be submitted to a
candid world. He has refused his Assent to Laws, the most wholesome and necessary for the
public good.
He has forbidden his Governors to pass Laws of immediate and pressing
importance, unless suspended in their operation till his Assent should be obtained;
and when so suspended, he has utterly neglected to attend to them.

He has refused to pass other Laws for the accommodation of large districts of
people, unless those people would relinquish the right of Representation in the
Legislature, a right inestimable to them and formidable to tyrants only.

He has called together legislative bodies at places unusual, uncomfortable, and distant
from the depository of their public Records, for the sole purpose of fatiguing them into
compliance with his measures.

# 3. Working with Excel

In [12]:
import glob, os

from openpyxl import load_workbook

currentworkingdirectory = os.getcwd()
parentdirectory = os.path.abspath(os.path.join(currentworkingdirectory, os.pardir))
downloadfolderdirectory = os.path.abspath(os.path.join(parentdirectory, "00-Python-Text-Basics")) #local download folder
print(currentworkingdirectory)
print(parentdirectory)
print(downloadfolderdirectory)

os.chdir(downloadfolderdirectory) #change directory
for file in glob.glob("*.xlsx"):
    print(file)

    wb = load_workbook(filename=file, read_only=True, data_only=True) #get workbook
    #wb.sheetnames
    #ws = wb.active #get worksheet
    #ws.title
    #ws["A1"].value

    for ws in wb.worksheets:
        print("In this worksheet " + ws.title)
        for row in ws.rows:
            for cell in row:
                print(cell.value)

    # Close the workbook after reading
    wb.close()

C:\Users\Andy\Desktop\venv\testapp\Information Extraction\00-Python-Text-Basics
C:\Users\Andy\Desktop\venv\testapp\Information Extraction
C:\Users\Andy\Desktop\venv\testapp\Information Extraction\00-Python-Text-Basics
SampleData.xlsx
In this worksheet Instructions
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
Online Instruction Page
None
None
None
None
None
None
None
2
None
None
Sample Data for Excel
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
Related tutorials
None
None
None
None
None
None
None
None
None
None
Named Excel Tables
None
None
None
None
None
None
None
None
None
None
Data Entry Tips
None
None
None
None
None
None
None
None
None
None
More Excel Sample Files
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
Related Contextures Products
None
None
None
None
None
None
None
None
None
None
Contextures Excel Tools Add-in
None
None
None
None
None
None
None
None
None
None
Data Entry Popup Kit
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
Get weekly Excel tips, tutorials, videos, and news
None
None
None
None
None
None
None
None
None
None
Contextures Excel Newsletter
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
Notes
None
None
None
None
None
None
None
None
None
•
SalesOrders sheet has sales data for a fictional company, and each row represents an order.
None
None
None
None
None
None
None
None
None
•
The Total column could be changed to a formula, to multiply the Units and Cost columns.
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
In this worksheet SalesOrders
OrderDate
Region
Rep
Item
Units
Unit Cost
Total
2019-01-06 00:00:00
East
Jones
Pencil
95
1.99
189.05
2019-01-23 00:00:00
Central
Kivell
Binder
50
19.99
999.4999999999999
2019-02-09 00:00:00
Central
Jardine
Pencil
36
4.99
179.64000000000001
2019-02-26 00:00:00
Central
Gill
Pen
27
19.99
539.7299999999999
2019-03-15 00:00:00
West
Sorvino
Pencil
56
2.99
167.44
2019-04-01 00:00:00
East
Jones
Binder
60
4.99
299.40000000000003
2019-04-18 00:00:00
Central
Andrews
Pencil
75
1.99
149.25
2019-05-05 00:00:00
Central
Jardine
Pencil
90
4.99
449.1
2019-05-22 00:00:00
West
Thompson
Pencil
32
1.99
63.68
2019-06-08 00:00:00
East
Jones
Binder
60
8.99
539.4
2019-06-25 00:00:00
Central
Morgan
Pencil
90
4.99
449.1
2019-07-12 00:00:00
East
Howard
Binder
29
1.99
57.71
2019-07-29 00:00:00
East
Parent
Binder
81
19.99
1619.1899999999998
2019-08-15 00:00:00
East
Jones
Pencil
35
4.99
174.65
2019-09-01 00:00:00
Central
Smith
Desk
2
125
250
2019-09-18 00:00:00
East
Jones
Pen Set
16
15.99
255.84
2019-10-05 00:00:00
Central
Morgan
Binder
28
8.99
251.72
2019-10-22 00:00:00
East
Jones
Pen
64
8.99
575.36
2019-11-08 00:00:00
East
Parent
Pen
15
19.99
299.84999999999997
2019-11-25 00:00:00
Central
Kivell
Pen Set
96
4.99
479.04
2019-12-12 00:00:00
Central
Smith
Pencil
67
1.29
86.43
2019-12-29 00:00:00
East
Parent
Pen Set
74
15.99
1183.26
2020-01-15 00:00:00
Central
Gill
Binder
46
8.99
413.54
2020-02-01 00:00:00
Central
Smith
Binder
87
15
1305
2020-02-18 00:00:00
East
Jones
Binder
4
4.99
19.96
2020-03-07 00:00:00
West
Sorvino
Binder
7
19.99
139.92999999999998
2020-03-24 00:00:00
Central
Jardine
Pen Set
50
4.99
249.5
2020-04-10 00:00:00
Central
Andrews
Pencil
66
1.99
131.34
2020-04-27 00:00:00
East
Howard
Pen
96
4.99
479.04
2020-05-14 00:00:00
Central
Gill
Pencil
53
1.29
68.37
2020-05-31 00:00:00
Central
Gill
Binder
80
8.99
719.2
2020-06-17 00:00:00
Central
Kivell
Desk
5
125
625
2020-07-04 00:00:00
East
Jones
Pen Set
62
4.99
309.38
2020-07-21 00:00:00
Central
Morgan
Pen Set
55
12.49
686.95
2020-08-07 00:00:00
Central
Kivell
Pen Set
42
23.95
1005.9
2020-08-24 00:00:00
West
Sorvino
Desk
3
275
825
2020-09-10 00:00:00
Central
Gill
Pencil
7
1.29
9.030000000000001
2020-09-27 00:00:00
West
Sorvino
Pen
76
1.99
151.24
2020-10-14 00:00:00
West
Thompson
Binder
57
19.99
1139.4299999999998
2020-10-31 00:00:00
Central
Andrews
Pencil
14
1.29
18.060000000000002
2020-11-17 00:00:00
Central
Jardine
Binder
11
4.99
54.89
2020-12-04 00:00:00
Central
Jardine
Binder
94
19.99
1879.06
2020-12-21 00:00:00
Central
Andrews
Binder
28
4.99
139.72
In this worksheet SampleNumbers
None
None
Sample Data -- Formatted Numbers
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
This example shows how Excel changes number formatting.
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
Click on the Text Box to select it
None
None
None
None
Paste the numbers in the cells below
None
None
None
None
None
Then, select the numbers and copy them
None
None
None
None
 -- Some numbers will change to dates,
None
None
None
None
None
None
None
None
None
None
 -- Leading zeroes will be lost.
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
For more information:
None
None
None
None
None
None
None
None
None
None
None
Data Entry Tips
 -- How to paste formatted numbers and keep the formatting
None
None
None
None
None
None
None
In this worksheet MyLinks
None
None
None
None
Contextures Products
None
None
Pivot Power Premium Add-in
Time-saving tools for pivot table power users
None
UserForms for Data Entry ebook Kit
Step by step instructions and videos
None
Contextures Excel Tools Add-in
Make instant backups, sort sheets, and many more tools
None
Data Entry Search Popup
Makes data entry easier when choosing from long list
None
Data Entry Popup
Select single or multiple items from a listbox, to enter in a single cell
None
30 Excel Functions in 30 Days eBook Kit
Sample workbook and easy to follow user guide for key Excel functions
None
None
None
None
Contextures Sites & News
None
None
Contextures Excel Newsletter
Weekly Excel tips, tutorials, videos, and news
None
Contextures Excel Tips Website
Hundreds of tutorials, tips and sample files
None
Contextures Excel Blog
Read the Excel tutorials and share your comments
None
Excel Pivot Tables Blog
Pivot table tutorials and tips, with comments and questions
None
None
None
None
Other Excel Products
None
None
Contextures Recommends
Other Excel tools and training, recommended by Debra